title: datastructures-js
email: eyas.ranjous@gmail.com
description: production-ready data structures implementation in javascript with typescript support.
baseurl: ""
url: ""
github_username:  eyas.ranjous
theme: jekyll-theme-tactile
author: Eyas Ranjous
logo: "/assets/images/ds-logo.png"
gems:
  - jekyll-seo-tag
